steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "***********************"
        echo "APPLY is set as : $_APPLY -- changes are applied only if set to true"
        echo "***********************"
  - id: 'tf init'
    name: 'hashicorp/terraform:0.12.29'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform init

  # [START tf-plan]
  - id: 'tf plan'
    name: 'hashicorp/terraform:0.12.29'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform plan
  # [END tf-plan]

  # [START tf-apply]
  - id: 'tf destroy'
    name: 'hashicorp/terraform:0.12.29'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ $_APPLY == 'true' ]; then
          cd terraform
          terraform destroy -auto-approve
        else
          echo "***************************** SKIPPING APPLYING *******************************"
          echo "apply '$_APPLY' is not set to true"
          echo "*******************************************************************************"
        fi
# [END tf-apply]