steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "***********************"
        echo "$apply"
        echo "***********************"
  - id: 'tf init'
    name: 'hashicorp/terraform:0.11.14'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform init

  # [START tf-plan]
  - id: 'tf plan'
    name: 'hashicorp/terraform:0.11.14'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform plan
  # [END tf-plan]

  # [START tf-apply]
  - id: 'tf apply'
    name: 'hashicorp/terraform:0.11.14'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        if [ $apply eq 'true' ]; then
          cd terraform
          terraform apply -auto-approve
        else
          echo "***************************** SKIPPING APPLYING *******************************"
          echo "apply '$apply' is not set to true"
          echo "*******************************************************************************"
        fi
# [END tf-apply]