steps:
  - name: 'maven'
    entrypoint: 'mvn'
    args: ['install']
  - name: 'gcr.io/$PROJECT_ID/packer'
    args:
      - build
      - -force
      - -var
      - project_id=$PROJECT_ID
      - packer.json